# Generated by Django 3.0.6 on 2020-05-21 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time_of_origin', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('N', 'New'), ('P', 'In Progress'), ('D', 'Done'), ('I', 'Invalid')], max_length=1)),
                ('completed_by', models.ForeignKey(null=True, on_delete=models.SET('Deleted user'), related_name='completed_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=models.SET('Deleted user'), related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
