# Generated by Django 3.0.6 on 2020-05-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='owner',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='reporter',
            new_name='reported_by',
        ),
    ]
