# Generated by Django 3.0.6 on 2020-05-21 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20200521_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time_of_origin',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
