# Generated by Django 3.0.6 on 2020-05-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_auto_20200521_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time_of_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
